version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/zugent/
permissions:
  - object: /var/www/zugent/
    pattern: "**"
    owner: www-data
    group: www-data
hooks:
  AfterInstall:
    - location: bin/dev_deploy.sh
      timeout: 30
